version: '3.8'

services:
  # Backend NestJS API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aws-cicd-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - FRONTEND_URL=http://localhost:3000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { hostname: 'localhost', port: 8000, path: '/health', timeout: 5000 }; const req = http.request(options, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.on('timeout', () => { req.destroy(); process.exit(1); }); req.setTimeout(5000); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aws-cicd-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development Backend (optional)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: aws-cicd-backend-dev
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - FRONTEND_URL=http://localhost:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    command: npm run start:dev
    networks:
      - app-network
    profiles: ["dev"]

  # Development Frontend (optional)
  frontend-dev:
    image: node:24-alpine
    container_name: aws-cicd-frontend-dev
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:8001
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - app-network
    profiles: ["dev"]
    depends_on:
      - backend-dev

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend: