AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Infrastructure for AWS CI/CD Pipeline - Creates VPC with DNS enabled'

Parameters:
  ProjectName:
    Type: String
    Default: 'aws-cicd'
    Description: 'Name prefix for all resources' 

  VpcCidr:
    Type: String 
    Default: '10.0.0.0/16'
    Description: 'CIDR block for the VPC'

Resources:
  # Main VPC - the foundation of your network 
  MainVPC:
    Type: AWS::EC2::VPC 
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true 
      EnableDnsSupport: true 
      Tags:
        - Key: Name 
          Value: !Sub '${ProjectName}-vpc' 
        - Key: Project 
          Value: !Ref ProjectName
  # Public Subnet in Availability Zone A
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-1a'
        - Key: Type
          Value: 'Public'
        - Key: Project
          Value: !Ref ProjectName

  # Public Subnet in Availability Zone B  
  PublicSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-1b'
        - Key: Type
          Value: 'Public'
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  VPCId:
    Description: 'VPC ID for use in other templates'
    Value: !Ref MainVPC
    Export:
      Name: !Sub '${ProjectName}-vpc-id'

  VPCCidr:
    Description: 'VPC CIDR block'
    Value: !Ref VpcCidr
    Export:
      Name: !Sub '${ProjectName}-vpc-cidr'
